name: Features of Lahore AQI data

on:
  # Runs every day at 2:00 PM Pakistan time (which is 9:00 AM UTC)
  schedule:
    - cron: '0 10 * * *'
  # Allows manual trigger
  workflow_dispatch:

permissions:
  contents: write  # Needed for committing changes
  
jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AQI Features script
        run: python compute_features.py

      - name: Commit updated CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add lahore_aqi_features.csv || echo "No changes to add"
          git commit -m "📊 Daily AQI update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
